# This file contains configurations for the gazebo joint velocity control

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    motion_controller:
      type: velocity_controllers/JointGroupVelocityController

    manipulator_controller: 
      type: velocity_controllers/JointGroupVelocityController
      
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


motion_controller:
  ros__parameters:
    joints:
      - back_right_wheel_joint
      - back_left_wheel_joint
      - front_right_wheel_joint
      - front_left_wheel_joint
      - center_link
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity 

manipulator_controller:
  ros__parameters:
    joints:
      - boom_angle
      - telescope_length
      - fork_angle
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort 
      
#joint_trajectory_controller:
#  ros__parameters:
#    joints:
#      - boom_angle
#      - telescope_length
#      - fork_angle
#    command_interfaces:
#      - position
#      - velocity
#    state_interfaces:
#      - position
#      - velocity
  
